/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        cargarFichaMemoMascota();
        cargarFichaMemoCliente();
        cargarFichaMemoVisita();
        cargarFichaMemoTratamiento();
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jpBusquedaMain = new javax.swing.JPanel();
        jbBusqClientes = new javax.swing.JButton();
        jbBusqMascotas = new javax.swing.JButton();
        jbBusqVisitas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbNuevoCliente = new javax.swing.JButton();
        jbNuevoMascota = new javax.swing.JButton();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/Escritorio.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jPanel3 = new javax.swing.JPanel();
        jbLoggout = new javax.swing.JButton();
        jbLoggin = new javax.swing.JButton();
        jlAvatar = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jtPw = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpMemoCliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfMemoClienteID = new javax.swing.JTextField();
        jtfMemoTelefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfMemoClienteNombre = new javax.swing.JTextField();
        jtfMemoClienteDNI = new javax.swing.JTextField();
        jtfMemoClienteApellido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jpMemoVisita = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfMemoVisitaID = new javax.swing.JTextField();
        jpMemoMascota = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtfMemoMascotaId = new javax.swing.JTextField();
        jtfMemoPesoProm = new javax.swing.JTextField();
        jtfMemoAlias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfMemoEdad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfMemoEspecie = new javax.swing.JTextField();
        jtfMemoRaza = new javax.swing.JTextField();
        jpMemoTratamiento = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbBusqClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/buscarCliente.png"))); // NOI18N
        jbBusqClientes.setText("Clientes");
        jbBusqClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusqClientesActionPerformed(evt);
            }
        });

        jbBusqMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/buscarMascota.png"))); // NOI18N
        jbBusqMascotas.setText("Mascotas");
        jbBusqMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusqMascotasActionPerformed(evt);
            }
        });

        jbBusqVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/buscarVisitas.png"))); // NOI18N
        jbBusqVisitas.setText("Visitas");
        jbBusqVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusqVisitasActionPerformed(evt);
            }
        });

        jLabel4.setText("CREAR:");

        jLabel5.setText("BUSQUEDA:");

        jbNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nuevo cliente.png"))); // NOI18N
        jbNuevoCliente.setText("New Cliente");
        jbNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoClienteActionPerformed(evt);
            }
        });

        jbNuevoMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nuevoMascota.png"))); // NOI18N
        jbNuevoMascota.setText("New Mascota");
        jbNuevoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBusquedaMainLayout = new javax.swing.GroupLayout(jpBusquedaMain);
        jpBusquedaMain.setLayout(jpBusquedaMainLayout);
        jpBusquedaMainLayout.setHorizontalGroup(
            jpBusquedaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBusquedaMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpBusquedaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jbNuevoMascota)
                    .addComponent(jbNuevoCliente)
                    .addComponent(jbBusqVisitas)
                    .addComponent(jbBusqMascotas)
                    .addComponent(jbBusqClientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBusquedaMainLayout.setVerticalGroup(
            jpBusquedaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBusquedaMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBusqClientes)
                .addGap(18, 18, 18)
                .addComponent(jbBusqMascotas)
                .addGap(18, 18, 18)
                .addComponent(jbBusqVisitas)
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbNuevoMascota)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jbLoggout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/cerrar-sesion.png"))); // NOI18N
        jbLoggout.setText("Loggout");
        jbLoggout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoggoutActionPerformed(evt);
            }
        });

        jbLoggin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Avatar/usuario24.png"))); // NOI18N
        jbLoggin.setText("Loggin");
        jbLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogginActionPerformed(evt);
            }
        });

        jlAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Avatar/monstruo64.png"))); // NOI18N
        jlAvatar.setText("jLabel1");

        jtPw.setText("jPasswordField1");

        jLabel2.setText("USUARIO:");

        jLabel3.setText("PW:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 601, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLoggin)
                .addGap(18, 18, 18)
                .addComponent(jbLoggout)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLoggout)
                    .addComponent(jbLoggin)
                    .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel13.setText("CLIENTE");

        jLabel14.setText("ID");

        jtfMemoClienteID.setEditable(false);
        jtfMemoClienteID.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfMemoTelefono.setEditable(false);
        jtfMemoTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel15.setText("DNI");

        jtfMemoClienteNombre.setEditable(false);
        jtfMemoClienteNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtfMemoClienteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMemoClienteNombreActionPerformed(evt);
            }
        });

        jtfMemoClienteDNI.setEditable(false);
        jtfMemoClienteDNI.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfMemoClienteApellido.setEditable(false);
        jtfMemoClienteApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtfMemoClienteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMemoClienteApellidoActionPerformed(evt);
            }
        });

        jLabel16.setText("TEL.");

        javax.swing.GroupLayout jpMemoClienteLayout = new javax.swing.GroupLayout(jpMemoCliente);
        jpMemoCliente.setLayout(jpMemoClienteLayout);
        jpMemoClienteLayout.setHorizontalGroup(
            jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMemoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jtfMemoClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMemoClienteLayout.createSequentialGroup()
                        .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpMemoClienteLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jtfMemoClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15))
                                .addGroup(jpMemoClienteLayout.createSequentialGroup()
                                    .addComponent(jtfMemoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel16))
                                .addComponent(jtfMemoClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfMemoClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpMemoClienteLayout.setVerticalGroup(
            jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMemoClienteLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addComponent(jtfMemoClienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfMemoClienteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMemoClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jtfMemoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMemoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfMemoClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jpMemoVisita.setPreferredSize(new java.awt.Dimension(268, 259));

        jLabel17.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel17.setText("VISITA");

        jLabel18.setText("ID");

        jtfMemoVisitaID.setEditable(false);
        jtfMemoVisitaID.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtfMemoVisitaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMemoVisitaIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMemoVisitaLayout = new javax.swing.GroupLayout(jpMemoVisita);
        jpMemoVisita.setLayout(jpMemoVisitaLayout);
        jpMemoVisitaLayout.setHorizontalGroup(
            jpMemoVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoVisitaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jtfMemoVisitaID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jpMemoVisitaLayout.setVerticalGroup(
            jpMemoVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoVisitaLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jpMemoVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jtfMemoVisitaID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jpMemoMascota.setPreferredSize(new java.awt.Dimension(268, 266));

        jLabel7.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel7.setText("MASCOTA");

        jtfMemoMascotaId.setEditable(false);
        jtfMemoMascotaId.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfMemoPesoProm.setEditable(false);
        jtfMemoPesoProm.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtfMemoAlias.setEditable(false);
        jtfMemoAlias.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel10.setText("ID");

        jLabel11.setText("Edad");

        jtfMemoEdad.setEditable(false);
        jtfMemoEdad.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel12.setText("Peso Prom.");

        jtfMemoEspecie.setEditable(false);
        jtfMemoEspecie.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtfMemoEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMemoEspecieActionPerformed(evt);
            }
        });

        jtfMemoRaza.setEditable(false);
        jtfMemoRaza.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpMemoMascotaLayout = new javax.swing.GroupLayout(jpMemoMascota);
        jpMemoMascota.setLayout(jpMemoMascotaLayout);
        jpMemoMascotaLayout.setHorizontalGroup(
            jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoMascotaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMemoMascotaLayout.createSequentialGroup()
                        .addComponent(jtfMemoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jtfMemoPesoProm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfMemoAlias, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpMemoMascotaLayout.createSequentialGroup()
                        .addComponent(jtfMemoRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpMemoMascotaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfMemoMascotaId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfMemoEspecie, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(24, 24, 24))
        );
        jpMemoMascotaLayout.setVerticalGroup(
            jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMemoMascotaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMemoMascotaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14))
                    .addGroup(jpMemoMascotaLayout.createSequentialGroup()
                        .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMemoMascotaId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jtfMemoAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jtfMemoEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMemoRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfMemoEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpMemoMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addComponent(jtfMemoPesoProm))
                .addGap(38, 38, 38))
        );

        jpMemoTratamiento.setPreferredSize(new java.awt.Dimension(268, 259));

        jLabel9.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel9.setText("TRATAMIENTO");

        javax.swing.GroupLayout jpMemoTratamientoLayout = new javax.swing.GroupLayout(jpMemoTratamiento);
        jpMemoTratamiento.setLayout(jpMemoTratamientoLayout);
        jpMemoTratamientoLayout.setHorizontalGroup(
            jpMemoTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoTratamientoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jpMemoTratamientoLayout.setVerticalGroup(
            jpMemoTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMemoTratamientoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel9)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jpBusquedaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpMemoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpMemoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpMemoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpMemoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpBusquedaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpMemoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpMemoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpMemoVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpMemoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbBusqClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusqClientesActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        BusquedaCliente bc = new BusquedaCliente();

        bc.setVisible(true);
        jDesktopPane1.add(bc);

    }//GEN-LAST:event_jbBusqClientesActionPerformed

    private void jbLoggoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoggoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLoggoutActionPerformed

    private void jbLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogginActionPerformed


    }//GEN-LAST:event_jbLogginActionPerformed

    private void jbNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GuardarNuevos nc = new GuardarNuevos();
        nc.setVisible(true);
        jDesktopPane1.add(nc);

    }//GEN-LAST:event_jbNuevoClienteActionPerformed

    private void jbNuevoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoMascotaActionPerformed
    jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GuardarNuevos nc = new GuardarNuevos();
        nc.setVisible(true);
        jDesktopPane1.add(nc);

    }//GEN-LAST:event_jbNuevoMascotaActionPerformed

    private void jbBusqMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusqMascotasActionPerformed
    jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        BusquedaMascota bm = new BusquedaMascota();
        bm.setVisible(true);
        jDesktopPane1.add(bm);

    }//GEN-LAST:event_jbBusqMascotasActionPerformed

    private void jbBusqVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusqVisitasActionPerformed
       
//        JpanelImage memo = new JpanelImage(jpVisitaMemo, "/Imagenes/memo250.png");
//        jpVisitaMemo.add(memo).repaint();
//        jpVisitaMemo.setOpaque(false);
//        jpVisitaMemo.setBorder(null);
//        jpVisitaMemo.setBackground(new Color(0, 0, 0, 0));
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        BusquedaVisita bv = new BusquedaVisita();
        bv.setVisible(true);
        jDesktopPane1.add(bv);

    }//GEN-LAST:event_jbBusqVisitasActionPerformed

    private void jtfMemoEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMemoEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMemoEspecieActionPerformed

    private void jtfMemoClienteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMemoClienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMemoClienteNombreActionPerformed

    private void jtfMemoClienteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMemoClienteApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMemoClienteApellidoActionPerformed

    private void jtfMemoVisitaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMemoVisitaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMemoVisitaIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbBusqClientes;
    private javax.swing.JButton jbBusqMascotas;
    private javax.swing.JButton jbBusqVisitas;
    private javax.swing.JButton jbLoggin;
    private javax.swing.JButton jbLoggout;
    private javax.swing.JButton jbNuevoCliente;
    private javax.swing.JButton jbNuevoMascota;
    private javax.swing.JLabel jlAvatar;
    private javax.swing.JPanel jpBusquedaMain;
    public static javax.swing.JPanel jpMemoCliente;
    public static javax.swing.JPanel jpMemoMascota;
    public static javax.swing.JPanel jpMemoTratamiento;
    public static javax.swing.JPanel jpMemoVisita;
    private javax.swing.JPasswordField jtPw;
    private javax.swing.JTextField jtUser;
    public static javax.swing.JTextField jtfMemoAlias;
    public static javax.swing.JTextField jtfMemoClienteApellido;
    public static javax.swing.JTextField jtfMemoClienteDNI;
    public static javax.swing.JTextField jtfMemoClienteID;
    public static javax.swing.JTextField jtfMemoClienteNombre;
    public static javax.swing.JTextField jtfMemoEdad;
    public static javax.swing.JTextField jtfMemoEspecie;
    public static javax.swing.JTextField jtfMemoMascotaId;
    public static javax.swing.JTextField jtfMemoPesoProm;
    public static javax.swing.JTextField jtfMemoRaza;
    public static javax.swing.JTextField jtfMemoTelefono;
    public static javax.swing.JTextField jtfMemoVisitaID;
    // End of variables declaration//GEN-END:variables
 public void cargarFichaMemoMascota() {                                 //HAY Q HACER CUSTOM CODE DEL PANEL Y PONERLOS PUBLIC Y STATIC
        MenuPrincipal.jpMemoMascota.setVisible(true);
        JpanelImage memo = new JpanelImage(MenuPrincipal.jpMemoMascota, "/Imagenes/memo250.png");
        MenuPrincipal.jpMemoMascota.add(memo).repaint();
        MenuPrincipal.jpMemoMascota.setOpaque(false);
        MenuPrincipal.jpMemoMascota.setBorder(null);
        MenuPrincipal.jpMemoMascota.setBackground(new Color(0, 0, 0, 0));

    }

    public void cargarFichaMemoCliente() {                                  //HAY Q HACER CUSTOM CODE DEL PANEL Y PONERLOS PUBLIC Y STATIC
        MenuPrincipal.jpMemoCliente.setVisible(true);
        JpanelImage memo = new JpanelImage(MenuPrincipal.jpMemoCliente, "/Imagenes/memo250.png");
        MenuPrincipal.jpMemoCliente.add(memo).repaint();
        MenuPrincipal.jpMemoCliente.setOpaque(false);
        MenuPrincipal.jpMemoCliente.setBorder(null);
        MenuPrincipal.jpMemoCliente.setBackground(new Color(0, 0, 0, 0));

    }
    public void cargarFichaMemoVisita() {
        MenuPrincipal.jpMemoVisita.setVisible(true);                        //HAY Q HACER CUSTOM CODE DEL PANEL Y PONERLOS PUBLIC Y STATIC
        JpanelImage memo = new JpanelImage(MenuPrincipal.jpMemoVisita, "/Imagenes/memo250.png");
        MenuPrincipal.jpMemoVisita.add(memo).repaint();
        MenuPrincipal.jpMemoVisita.setOpaque(false);
        MenuPrincipal.jpMemoVisita.setBorder(null);
        MenuPrincipal.jpMemoVisita.setBackground(new Color(0, 0, 0, 0));

    }
    
     public void cargarFichaMemoTratamiento() {
        MenuPrincipal.jpMemoTratamiento.setVisible(true);                        //HAY Q HACER CUSTOM CODE DEL PANEL Y PONERLOS PUBLIC Y STATIC
        JpanelImage memo = new JpanelImage(MenuPrincipal.jpMemoTratamiento, "/Imagenes/memo250.png");
        MenuPrincipal.jpMemoTratamiento.add(memo).repaint();
        MenuPrincipal.jpMemoTratamiento.setOpaque(false);
        MenuPrincipal.jpMemoTratamiento.setBorder(null);
        MenuPrincipal.jpMemoTratamiento.setBackground(new Color(0, 0, 0, 0));

    }
    
    
public static void borrarCamposMascota(){
    jtfMemoMascotaId.setText("");
    jtfMemoAlias.setText("");
    jtfMemoEspecie.setText("");
    jtfMemoPesoProm.setText("");
    jtfMemoRaza.setText("");
    jtfMemoEdad.setText("");
    
}
public static void borrarCamposCliente(){
    jtfMemoClienteID.setText("");
    jtfMemoClienteApellido.setText("");
    jtfMemoClienteDNI.setText("");
    jtfMemoClienteNombre.setText("");
    jtfMemoTelefono.setText("");
   
    
}

}
